# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "batchers-master"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  # tomcat presentation app
  config.vm.network "forwarded_port", guest: 9090, host: 9090
  # jetty (stub web service) 
  config.vm.network "forwarded_port", guest: 9091, host: 9091
  # mysql
  config.vm.network "forwarded_port", guest: 3306, host: 3306
  # rabbitmq
  config.vm.network "forwarded_port", guest: 5672, host: 5672
  # rabbitmq admin
  config.vm.network "forwarded_port", guest: 15672, host: 15672

  # config.vm.network "private_network", ip: "192.168.0.4"

  config.vm.provision "file", source: "scripts", destination: "scripts"
  config.vm.provision "file", source: "rabbitmq-signing-key-public.asc", destination: "rabbitmq-signing-key-public.asc"
  config.vm.provision "shell", path: "provision.sh"

end
