# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "batchers-master"
  config.vm.box_url = "https://oss-binaries.phusionpassenger.com/vagrant/boxes/latest/ubuntu-14.04-amd64-vbox.box"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end

  config.vm.provision "file", source: "scripts", destination: "scripts"
  config.vm.provision "shell", path: "provision.sh"

  # add default master IP for slave if it is not present
  batchers_master_ip=ENV['BATCHERS_MASTER_IPBATCHERS_MASTER_IP'] || "192.168.50.4"

  config.vm.define "standalone", primary: true do |standalone|
    # for standalone default to localhost
    batchers_master_ip="127.0.0.1"

    puts "Vagrantfile setting BATCHERS_MASTER_IP to #{batchers_master_ip}"

    # tomcat presentation app
    standalone.vm.network "forwarded_port", guest: 9090, host: 9090
    # jetty (stub web service) 
    standalone.vm.network "forwarded_port", guest: 9091, host: 9091
    # mysql
    standalone.vm.network "forwarded_port", guest: 3306, host: 3306
    # rabbitmq
    standalone.vm.network "forwarded_port", guest: 5672, host: 5672
    # rabbitmq admin
    standalone.vm.network "forwarded_port", guest: 15672, host: 15672

    standalone.vm.provision "shell", inline: "export BATCHERS_MASTER_IP=#{batchers_master_ip} && export BATCHERS_PROFILE=standalone && . scripts/provision_with_variables.sh"
  end

  config.vm.define "master", autostart: false do |master|
    puts "Vagrantfile setting BATCHERS_MASTER_IP to #{batchers_master_ip}"

    # tomcat presentation app
    master.vm.network "forwarded_port", guest: 9090, host: 9090
    # jetty (stub web service) 
    master.vm.network "forwarded_port", guest: 9091, host: 9091
    # mysql
    master.vm.network "forwarded_port", guest: 3306, host: 3306
    # rabbitmq
    master.vm.network "forwarded_port", guest: 5672, host: 5672
    # rabbitmq admin
    master.vm.network "forwarded_port", guest: 15672, host: 15672

    master.vm.network "private_network", ip: "192.168.50.4"

    master.vm.provision "shell", inline: "export BATCHERS_MASTER_IP=#{batchers_master_ip} && export BATCHERS_PROFILE=master && . scripts/provision_with_variables.sh"
  end

  config.vm.define "slave", autostart: false do |slave|

    puts "Vagrantfile setting BATCHERS_MASTER_IP to #{batchers_master_ip}"

    # tomcat presentation app
    slave.vm.network "forwarded_port", guest: 9090, host: 19090
    slave.vm.provision "shell", inline: "export BATCHERS_MASTER_IP=#{batchers_master_ip} && export BATCHERS_PROFILE=slave && . scripts/provision_with_variables.sh"
  end

end
